# Generated by Django 3.1.2 on 2020-11-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='level',
            field=models.CharField(choices=[('J', 'Junior developer'), ('M', 'Middle developer'), ('S', 'Senior developer')], max_length=1),
        ),
    ]
