# Generated by Django 3.1.2 on 2020-11-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_category_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='pass_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
